# The name of the workflow
    name: Image Accesibility Reviewer
    # What conditions trigger the workflow
    #  In this case, all pushes and pull requests
    description: github action to check if all images have non-empty alt tags
    on: [push, pull_request]
    # The jobs that will be run, usually in parallel
    branding:
      icon: 'image'
      color: 'blue'
    jobs:
      

name: 'Image Accesibility Reviewer'
description: 'Check if image have non-empt alt tags'
on: [push, pull_request]
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'